In [2]:
import numpy as np

## numpy array

In [3]:
benimListem = [20,30,40]

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi = [[10,20,30],[40,50,60],[70,80,90]]

In [6]:
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## arange *

In [7]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,12,2) #step size 2 

array([ 0,  2,  4,  6,  8, 10])

## zeros

In [11]:
## 0 oluşturuyor.


In [13]:
np.zeros(5) # 5 tane 0 oluşturdu

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,2)) ##dizi içerisinde dizi matrix

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones(5) # 5 tane 1 oldu

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace *

In [26]:
## Belirttiğiniz numaralar arasında evenly space manasına gelen, eşit olarak boyutlandırılmış, eşit olarak aralık bırakılmış
## şekilde bir dizi oluşturuyor. #NOT: Önemli olan konulara * sembolü bıraktım.

In [27]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

## eye

In [25]:
np.eye(3) ## matrixle ilgili lineer cebir işlemi yapacaksak kullanabiliriz.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [28]:
## normal dağılıma uygun rastgele değerler üretiyor.

In [31]:
np.random.randn(4) #tek boyutlu

array([ 0.55543773,  1.60499151, -0.68252039, -1.6211494 ])

In [33]:
np.random.randn(4,4)

array([[ 0.21916175, -0.80990514, -1.34396217,  1.07644165],
       [ 0.86026488, -0.19802245,  1.17589428,  1.46520095],
       [-0.21995041,  1.09357508,  0.87028361,  0.4492694 ],
       [ 2.47809963, -0.95772738,  0.51108868, -0.22166705]])

In [42]:
np.random.randint(1,8) #8 dönmeyecektir.

7

In [44]:
np.random.randint(1,10,3) #1 ile 10 arasında rastgele 3 değer döndürüyor.

array([3, 7, 2])

In [45]:
benimNumpyDizim = np.arange(20)

In [46]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
benimRandomDizim = np.random.randint(0,100,30)

In [51]:
benimRandomDizim

array([75, 43, 26, 61, 53, 98, 51, 41, 49, 77, 21, 59, 39, 51, 69, 36,  3,
       89, 51, 86, 93, 69, 28, 59, 58, 89, 11, 27, 51, 60])

## numpy dizi methodları

In [54]:
benimNumpyDizim.reshape(4,5) #reshape yeniden şekillendir demek

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
benimNumpyDizim.max()

19

In [56]:
benimRandomDizim.max()

98

In [57]:
benimRandomDizim.min()

3

In [58]:
benimNumpyDizim.min()

0

In [60]:
benimRandomDizim.argmax() # 5.indexde 98 değeri yer almakta 

5

In [61]:
benimRandomDizim.argmin()

16

In [62]:
reshapeDizim = benimNumpyDizim.reshape(5,4)

In [64]:
reshapeDizim.shape

(5, 4)