In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [5]:
benimDizim[2:7]

array([2, 3, 4, 5, 6])

In [6]:
benimDizim[2:7] = -1

In [7]:
benimDizim

array([ 0,  1, -1, -1, -1, -1, -1,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
baskaDizi = np.arange(0,15)

In [9]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
slicingDizisi = baskaDizi[5:9]

In [11]:
slicingDizisi

array([5, 6, 7, 8])

In [13]:
slicingDizisi[:] = 800

In [14]:
slicingDizisi

array([800, 800, 800, 800])

In [15]:
baskaDizi

array([  0,   1,   2,   3,   4, 800, 800, 800, 800,   9,  10,  11,  12,
        13,  14])

In [16]:
ornekDizi = np.arange(0,15)

In [17]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
ornekDiziKopyasi = ornekDizi.copy()

In [19]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:9]

In [23]:
ornekDiziKopyaSlicing[:] = 800

In [24]:
ornekDiziKopyaSlicing

array([800, 800, 800, 800, 800, 800])

In [25]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800, 800, 800, 800,   9,  10,  11,  12,
        13,  14])

In [26]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## matrix

In [30]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [31]:
benimMatrixDizim = np.array(benimListem)

In [32]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [33]:
benimMatrixDizim[0]

array([10, 20, 30])

In [34]:
benimMatrixDizim[1][2]

40

In [35]:
benimMatrixDizim[1,2]

40

In [40]:
benimMatrixDizim[2:,1:]

array([[50, 60]])

In [42]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [43]:
yeniMatrix = np.array(yeniListe)

In [44]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
yeniMatrix[3]

array([15, 16, 17, 18, 19])

In [47]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## numpy operasyonlar

In [53]:
yeniBirDizi = np.random.randint(1,100,20)

In [54]:
yeniBirDizi

array([97, 43, 59, 63, 98,  1, 48, 80, 64, 50, 20, 66, 75, 33, 74, 36,  9,
       52, 35, 54])

In [57]:
yeniBirDizi > 24

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True])

In [58]:
sonucDizisi = yeniBirDizi > 24

In [59]:
sonucDizisi

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True])

In [61]:
yeniBirDizi[sonucDizisi] #24 ten büyük sayıları listeliyor.

array([97, 43, 59, 63, 98, 48, 80, 64, 50, 66, 75, 33, 74, 36, 52, 35, 54])

In [62]:
sonDizi = np.arange(0,24)

In [63]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [64]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [65]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [66]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [67]:
sonDizi / sonDizi

C:\Users\sumey\AppData\Local\Temp\ipykernel_7200\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
np.sqrt(sonDizi) ## karekök almak için 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [71]:
np.max(sonDizi)

23

In [73]:
np.min(sonDizi)

0